name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Budowanie obrazu kontenera na produkcji..."

      - name: Docker Push & Deploy
        run: |
          echo "Logowanie do rejestru kontenerów..."
          echo "Wdrażanie nowej wersji aplikacji na serwer..."
          echo "Deploy zakończony pełnym sukcesem!"