name: Security Scan

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Security Tools
        run: pip install bandit safety

      - name: Run Bandit (Skanowanie kodu)
        run: bandit -r . -x ./venv || echo "Ostrzeżenia bandit"

      - name: Run Safety (Skanowanie bibliotek)
        run: safety check || echo "Skanowanie pakietów zakończone"